server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # 這一斷最重要：讓所有的路徑都導回 index.html，交給 Angular 路由處理
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 錯誤頁面設定 (選用)
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
